"""Content-driven connector-config scaffolding (v0.4.0 §D).

``legal-mcp scaffold-connector`` introspects a source's *real* columns via the
connector's ``describe_schema`` and emits a **draft** connector config. The draft
declares every discovered column, guesses the first column as the identity field,
leaves aliases blank, and sets ``record_scope.mode: none`` — the safe default for
an arbitrary table that maps onto no governance project.

Scaffolding never widens disclosure on its own: the draft is a starting point for
human review. The operator deletes sensitive columns, confirms the identity field
and scope, and commits. Only a column that survives review into the committed
config is ever queryable — the "only declared fields are queryable" posture holds.
"""

from __future__ import annotations

import json
from typing import Protocol

from legal_mcp.connectors.base import SourceTable


def _q(value: str) -> str:
    """Quote a string scalar so it is valid YAML for any source column name.

    YAML is a superset of JSON, so a JSON-encoded string is a correctly quoted
    and escaped YAML scalar — robust against spaces, CJK, colons, and quotes that
    real Bitable field names carry.
    """
    return json.dumps(value, ensure_ascii=False)

_HEADER = (
    "# Draft connector config — generated by `legal-mcp scaffold-connector` from\n"
    "# the source's real columns. REVIEW BEFORE USE: delete columns that must not\n"
    "# be queryable, confirm the identity field (is_identity), add aliases, and set\n"
    "# each domain's record_scope. A column is queryable only after you keep it here.\n"
)


class _Describable(Protocol):
    name: str

    def describe_schema(self) -> tuple[SourceTable, ...]: ...


def scaffold_connector_config(
    connector: _Describable,
    *,
    app_token: str,
    app_id_env: str = "FEISHU_APP_ID",
    app_secret_env: str = "FEISHU_APP_SECRET",
) -> str:
    """Render a draft connector YAML from ``connector.describe_schema()``.

    Only the ``feishu_bitable`` source type is emitted (the one configurable
    read-through source). The draft loads as-is via ``load_connector_config``;
    after a no-op review it serves every discovered column.
    """
    tables = connector.describe_schema()
    lines = [_HEADER, "version: 1", "sources:"]
    lines.append("  - type: feishu_bitable")
    lines.append(f"    app_token: {_q(app_token)}")
    lines.append(f"    app_id_env: {_q(app_id_env)}")
    lines.append(f"    app_secret_env: {_q(app_secret_env)}")
    lines.append("    domains:")
    for table in tables:
        lines.append(f"      - name: {_q(table.domain)}")
        lines.append(f"        table_id: {_q(table.table)}")
        lines.append("        record_scope: {mode: none}")
        if not table.fields:
            lines.append("        fields: []")
            continue
        lines.append("        fields:")
        for index, field in enumerate(table.fields):
            # First column is the guessed identity field (operator confirms).
            is_identity = "true" if index == 0 else "false"
            lines.append(
                f"          - {{name: {_q(field)}, is_identity: {is_identity}, aliases: []}}"
            )
    return "\n".join(lines) + "\n"
